### ISSUE TITLE
DateTime option serializes incorrectly to table storage

### ISSUE THREAD

**Issue by jackfoxy** [fsprojects/FSharp.Azure.Storage#12]
Serializes as string literal `Some(09/13/2015 14:32:10)`

See my modification to DataQueryTest ``querying for a record that has option type fields works`` in branch DateTimeOption of my fork for test case. https://github.com/jackfoxy/FSharp.Azure.Storage/tree/DateTimeOption

**Comment by daniel-chambers** [comment]
Thanks for reporting this. I originally didn't think it was possible, but I've looked into how table storage handles date times more closely, and it actually can be. See PR for more info.

**Comment by daniel-chambers** [comment]
This has been released in NuGet package v2.1.0.
