### ISSUE TITLE
.NET Core support

### ISSUE THREAD

**Issue by ian-moore** [fsprojects/FSharp.Azure.Storage#27]
I would like to use this in a .NET Core app, it would be nice if FSharp.Azure.Storage supported .NET Standard. I will take a look into this myself and see if it can be accomplished

**Comment by daniel-chambers** [comment]
Great; I've been hanging back from .NET Core while it's been tumultuous, but if you're willing to take a look and see what's required, that'd be awesome. :)

**Comment by ian-moore** [comment]
I am not an expert on .NET Core but here's what I'm seeing after making a quick attempt:

* Will have to target .NET Standard 2.0 (and thus needs .NET Core SDK 2.0 - still in preview) due to some properties on `Type` not available in previous .NET Standard versions.
* Unquote is not on .NET Standard yet, but the package can be added to a .NET Standard 2.0 library. I assume this limits deployment options.
* Updating `WindowsAzure.Storage` to a .NET Standard compatible version has some API changes. Hard for me to verify these since ionide-vscode doesn't have working intellisense for .NET Standard 2.0 yet. https://github.com/fsharp/FsAutoComplete/issues/180

I probably won't take this much further until .NET Standard 2.0 is complete.

**Comment by daniel-chambers** [comment]
Thanks for the investigation, that's great information to know. I think a quite a few F# things are backed up behind .NET Standard 2.0. We should definitely circle back once it's complete.

**Comment by daniel-chambers** [comment]
Yeah, now that .NET Standard 2.0 is out, this is definitely something I'll look at when I've got a chance. :)
