### ISSUE TITLE
Support for point query

### ISSUE THREAD

**Issue by AntoineGagne** [fsprojects/FSharp.Azure.Storage#38]
I didn't see it in the documentation but is there any support for [point queries](https://docs.microsoft.com/en-us/azure/storage/tables/table-storage-design-for-query)?

**Comment by daniel-chambers** [comment]
You should just be able to write a query filtering by the partition key and the row key only and that is a point query.

Have a look at [this part of the wiki](https://github.com/fsprojects/FSharp.Azure.Storage/wiki/Querying-Data-from-Table-Storage#filtering-with-where) to see how to do that.
