### ISSUE TITLE
Relax version constraint on FSharp.Control.AsyncSeq

### ISSUE THREAD

**Issue by toburger** [fsprojects/FSharp.Azure.Storage#46]
### Description

The dependency to FSharp.Control.AsyncSeq is version locked and you get a warning when using a newer version than 2.x of the library.

### Repro steps

`dotnet add package FSharp.Control.AsyncSeq --version 3.0.3`
`dotnet add package FSharp.Azure.Storage --version 5.0.1`

### Expected behavior

No warning

### Actual behavior

The following warning gets shown:

> warning NU1608: Detected package version outside of dependency constraint: FSharp.Azure.Storage 5.0.1 requires FSharp.Control.AsyncSeq (>= 2.0.0 && < 3.0.0) but version FSharp.Control.AsyncSeq 3.0.3 was resolved.

### Known workarounds

`dotnet add package FSharp.Control.AsyncSeq --version 2.0.24`

**Comment by daniel-chambers** [comment]
Unfortunately, that constraint is there for a reason. v3 of AsyncSeq abandoned the `netstandard2.0` target, which this project uses to ensure compatibility for .NET Framework users. AsyncSeq v3 only supports `netstandard2.1` which does not support .NET Framework. See [this post](https://github.com/fsprojects/FSharp.Control.AsyncSeq/issues/124#issuecomment-731751541) for more background.

**Comment by toburger** [comment]
Thanks for clarifying the reason about the restriction. 👍

**Comment by toburger** [comment]
Can this be relaxed, now that the `FSharp.Control.AsyncSeq` does target `netstandard2.0`?

**Comment by daniel-chambers** [comment]
Oh nice, yeah, I'll look into relaxing that constraint now.

**Comment by daniel-chambers** [comment]
This has been released in v5.0.2.
