### ISSUE TITLE
Rename FSharp.Azure to  ...?

### ISSUE THREAD

**Issue by dsyme** [fsprojects/FSharp.Azure.Storage#9]
We should revisit [this discussion](https://github.com/fsprojects/FSharp.Azure/issues/5#issuecomment-107128948) and finalize on a name for FSharp.Azure that meets the [guidelines](http://fsharp.github.io/2014/09/19/fsharp-libraries.html)

One suggestion was FSharp.Azure.Storage. Another could be FSharp.Azure.StorageCodeFirst.  I know these are a bit longer but that's for a reason - to make room for more technologies to come in under the FSharp.Azure namespace as the range of things available on Azure increases.

**Comment by isaacabraham** [comment]
I think FSharp.Azure.Storage too.

**Comment by daniel-chambers** [comment]
I also prefer FSharp.Azure.Storage.

How would you guys suggest renaming the NuGet package? I don't think NuGet has a facility for providing a redirect from an old package name to a new name? It seems a bit crappy just to drop a "deprecated - go use this new package" message in the package description and expect people to notice and switch packages... any suggestions?

**Comment by isaacabraham** [comment]
You could always leave the package the same and just change the namespaces in code. Microsoft did exactly did with a load of azure packages e.g. Service Bus and even Storage.

**Comment by daniel-chambers** [comment]
That's true, but they weren't renaming because of name collisions, they were renaming because of marketing (eg WindowsAzure.Storage). If we don't rename the package, are we achieving the goal intended here? 
@dsyme, have their been any other packages in the FSharp community that you know of that have undergone a similar rename? Did they rename their packages too?

**Comment by dsyme** [comment]
I'd say just put up the new package with new name and put "this package has been renamed" on the old one and remove all editions it from search (I still don't know an easy way to remove all the editions though).  People will transition ok. Once it's done it's done.

**Comment by isaacabraham** [comment]
You can't remove editions AFAIK - you can just stop them showing up in search results.

**Comment by dsyme** [comment]
Right that's what I meant.  But can you remove all of 100 versions from search all at once?

**Comment by daniel-chambers** [comment]
Okay, I'm currently renaming all the things; I'm thinking I should also drop the "DigitallyCreated." prefix off the namespace too, while I'm at it.

**Comment by dsyme** [comment]
That's great, thanks
